#include <iostream>
#include <fstream>
using namespace std;

int main(int argc, char *argv[]) {
	ofstream archI;
	archI.open("practicas_bio.txt");
	archI<<"6109"<<endl;	archI<<"UR"<<endl;	archI<<"Uremia"<<endl;	archI<<10<<endl;	archI<<50<<endl;
	archI<<"4993"<<endl;	archI<<"CREh"<<endl;	archI<<"Creatinina-Hombres"<<endl;	archI<<0.62<<endl;	archI<<0.79<<endl;
	archI<<"1069"<<endl;	archI<<"CREm"<<endl;	archI<<"Creatinina-Mujeres"<<endl;	archI<<0.41<<endl;	archI<<0.98<<endl;
	archI<<"3880"<<endl;	archI<<"Auh"<<endl;	archI<<"Acido urico-Hombres"<<endl;	archI<<1.2<<endl;	archI<<9.4<<endl;
	archI<<"1251"<<endl;	archI<<"Aum"<<endl;	archI<<"Acido Urico-Mujeres"<<endl;	archI<<1.6<<endl;	archI<<10.6<<endl;
	archI<<"8852"<<endl;	archI<<"GLU"<<endl;	archI<<"Glucosa: metodo enzimatico"<<endl;	archI<<70<<endl;	archI<<100<<endl;
	archI<<"4044"<<endl;	archI<<"CT"<<endl;	archI<<"Colesterol total: metodo bicromatico."<<endl;	archI<<0<<endl;	archI<<200<<endl;
	archI<<"1014"<<endl;	archI<<"HDL"<<endl;	archI<<"Colesterol HDL: metodo enzimatico."<<endl;	archI<<40<<endl;	archI<<60<<endl;
	archI<<"8216"<<endl;	archI<<"LDL"<<endl;	archI<<"Colesterol LDL: metodo enzimatico."<<endl;	archI<<0<<endl;	archI<<110<<endl;
	archI<<"6254"<<endl;	archI<<"VLDL"<<endl;	archI<<"Colesterol VLDL: sustraccion de los valores de HDL mas LDL del colesterol total."<<endl;	archI<<9.6<<endl;	archI<<54.8<<endl;
	archI<<"8935"<<endl;	archI<<"AAT"<<endl;	archI<<"Alfa-1 antitripsina"<<endl;	archI<<20<<endl;	archI<<53<<endl;
	archI<<"7044"<<endl;	archI<<"TGL"<<endl;	archI<<"Trigliceridos: metodo enzimatico."<<endl;	archI<<0<<endl;	archI<<150<<endl;
	archI<<"6413"<<endl;	archI<<"PROT"<<endl;	archI<<"Proteinas totales: reaccion de Biuret."<<endl;	archI<<5.6<<endl;	archI<<8.2<<endl;
	archI<<"8077"<<endl;	archI<<"ALB"<<endl;	archI<<"Albumina: metodo colorimetrico (Bromocresol)."<<endl;	archI<<3.5<<endl;	archI<<4.9<<endl;
	archI<<"2628"<<endl;	archI<<"GAM"<<endl;	archI<<"Gammaglobulinas: metodo turbidimetrico (La Huega)"<<endl;	archI<<0.48<<endl;	archI<<1.5<<endl;
	archI<<"5073"<<endl;	archI<<"CALT"<<endl;	archI<<"Calcio total: metodo colorimetrico"<<endl;	archI<<8<<endl;	archI<<10.5<<endl;
	archI<<"6823"<<endl;	archI<<"CALS"<<endl;	archI<<"Calcio serico"<<endl;	archI<<8.1<<endl;	archI<<10.4<<endl;
	archI<<"1899"<<endl;	archI<<"VITD"<<endl;	archI<<"25 Hidroxi-Vitamina D"<<endl;	archI<<0<<endl;	archI<<40<<endl;
	archI<<"7614"<<endl;	archI<<"TGOh"<<endl;	archI<<"Transaminasa Glutamico Oxalacetica-Hombre"<<endl;	archI<<0<<endl;	archI<<40<<endl;
	archI<<"3469"<<endl;	archI<<"TGOm"<<endl;	archI<<"Transaminasa Glutamico Oxalacetica-Mujer"<<endl;	archI<<0<<endl;	archI<<35<<endl;
	archI<<"3453"<<endl;	archI<<"TGPh"<<endl;	archI<<"Transaminasa Glutamico Piruvica-Hombre"<<endl;	archI<<0<<endl;	archI<<40<<endl;
	archI<<"1847"<<endl;	archI<<"TGPm"<<endl;	archI<<"Transaminasa Glutamico Piruvica-Mujer"<<endl;	archI<<0<<endl;	archI<<35<<endl;
	archI<<"1243"<<endl;	archI<<"ALP"<<endl;	archI<<"Fosfatasa alcalina"<<endl;	archI<<40<<endl;	archI<<130<<endl;
	archI<<"4192"<<endl;	archI<<"BT"<<endl;	archI<<"Bilirrubina Total"<<endl;	archI<<2<<endl;	archI<<14<<endl;
	archI<<"4481"<<endl;	archI<<"BD"<<endl;	archI<<"Bilirrubina Directa"<<endl;	archI<<0<<endl;	archI<<4<<endl;
	archI<<"6954"<<endl;	archI<<"TSHA"<<endl;	archI<<"Tirotrofina Adultos"<<endl;	archI<<0.4<<endl;	archI<<4.5<<endl;
	archI<<"6766"<<endl;	archI<<"TSHRN"<<endl;	archI<<"Tirotrofina RN a termino"<<endl;	archI<<1.3<<endl;	archI<<19<<endl;
	archI<<"6967"<<endl;	archI<<"TSHm1"<<endl;	archI<<"Tirotrofina 0-1 anio"<<endl;	archI<<0.9<<endl;	archI<<5.6<<endl;
	archI<<"1963"<<endl;	archI<<"TSHM1-5"<<endl;	archI<<"Tirotrofina 1-5 anios"<<endl;	archI<<0.65<<endl;	archI<<5.8<<endl;
	archI<<"1960"<<endl;	archI<<"TSH5-10"<<endl;	archI<<"Tirotrofina 5-10 anios"<<endl;	archI<<0.5<<endl;	archI<<4.8<<endl;
	archI<<"1317"<<endl;	archI<<"TSH10-15"<<endl;	archI<<"Tirotrofina 10-15 anios"<<endl;	archI<<0.55<<endl;	archI<<5.3<<endl;
	archI<<"4929"<<endl;	archI<<"FSHh"<<endl;	archI<<"Hormona Foliculo estimulante -Hombre"<<endl;	archI<<1<<endl;	archI<<12<<endl;
	archI<<"1124"<<endl;	archI<<"FSHMFF"<<endl;	archI<<"Hormona Foliculo estimulante -Mujer Fase folicular"<<endl;	archI<<3<<endl;	archI<<8.1<<endl;
	archI<<"1047"<<endl;	archI<<"FSHMFL"<<endl;	archI<<"Hormona Foliculo estimulante -Mujer Fase lutea"<<endl;	archI<<1.5<<endl;	archI<<5.5<<endl;
	archI<<"3719"<<endl;	archI<<"FSHMPO"<<endl;	archI<<"Hormona Foliculo estimulante -Mujer Pico ovulatorio"<<endl;	archI<<2.6<<endl;	archI<<17<<endl;
	archI<<"8435"<<endl;	archI<<"FSHMPM"<<endl;	archI<<"Hormona Foliculo estimulante -Mujer Post menopausia"<<endl;	archI<<27<<endl;	archI<<133.5<<endl;
	archI<<"8590"<<endl;	archI<<"ESTh"<<endl;	archI<<"Estradiol -Hombre"<<endl;	archI<<0<<endl;	archI<<45<<endl;
	archI<<"8597"<<endl;	archI<<"ESTMFF"<<endl;	archI<<"Estradiol-Mujer Fase folicular"<<endl;	archI<<25<<endl;	archI<<250<<endl;
	archI<<"1676"<<endl;	archI<<"ESTMFL"<<endl;	archI<<"Estradiol -Mujer Fase lutea"<<endl;	archI<<40<<endl;	archI<<650<<endl;
	archI<<"7153"<<endl;	archI<<"ESTMPO"<<endl;	archI<<"Estradiol-Mujer Pico ovulatorio"<<endl;	archI<<25<<endl;	archI<<310<<endl;
	archI<<"2382"<<endl;	archI<<"ESTMPM"<<endl;	archI<<"Estradiol-Mujer Post menopausia"<<endl;	archI<<0<<endl;	archI<<30<<endl;
	
	archI.close();
	
	ofstream arch;
	arch.open("localidades_er.txt");
	arch<<71<<endl;	arch<<"Valle Maria"<<endl;	arch<<751<<endl;
	arch<<14<<endl;	arch<<"Colon"<<endl;	arch<<1157<<endl;
	arch<<68<<endl;	arch<<"Tabossi"<<endl;	arch<<1797<<endl;
	arch<<39<<endl;	arch<<"Larroque"<<endl;	arch<<210<<endl;
	arch<<18<<endl;	arch<<"Crespo"<<endl;	arch<<1348<<endl;
	arch<<26<<endl;	arch<<"General Galarza"<<endl;	arch<<976<<endl;
	arch<<31<<endl;	arch<<"Gualeguay"<<endl;	arch<<1390<<endl;
	arch<<72<<endl;	arch<<"Viale"<<endl;	arch<<500<<endl;
	arch<<43<<endl;	arch<<"Lucas Gonzalez"<<endl;	arch<<1489<<endl;
	arch<<24<<endl;	arch<<"Federal"<<endl;	arch<<720<<endl;
	arch<<44<<endl;	arch<<"Maria Grande"<<endl;	arch<<255<<endl;
	arch<<81<<endl;	arch<<"Villa Paranacito"<<endl;	arch<<119<<endl;
	arch<<78<<endl;	arch<<"Villa Elisa"<<endl;	arch<<802<<endl;
	arch<<13<<endl;	arch<<"Colonia Elia"<<endl;	arch<<458<<endl;
	arch<<54<<endl;	arch<<"Puerto Yerua"<<endl;	arch<<504<<endl;
	arch<<77<<endl;	arch<<"Villa Dominguez"<<endl;	arch<<220<<endl;
	arch<<4<<endl;	arch<<"Aranguren"<<endl;	arch<<990<<endl;
	arch<<30<<endl;	arch<<"Gobernador Mansilla"<<endl;	arch<<899<<endl;
	arch<<23<<endl;	arch<<"Federacion"<<endl;	arch<<646<<endl;
	arch<<16<<endl;	arch<<"Concordia"<<endl;	arch<<1843<<endl;
	arch<<42<<endl;	arch<<"Los Conquistadores"<<endl;	arch<<470<<endl;
	arch<<56<<endl;	arch<<"San Benito"<<endl;	arch<<1488<<endl;
	arch<<6<<endl;	arch<<"Bovril"<<endl;	arch<<1100<<endl;
	arch<<51<<endl;	arch<<"Pueblo Brugo"<<endl;	arch<<732<<endl;
	arch<<57<<endl;	arch<<"San Gustavo"<<endl;	arch<<435<<endl;
	arch<<61<<endl;	arch<<"San Justo"<<endl;	arch<<307<<endl;
	arch<<34<<endl;	arch<<"Hernandez"<<endl;	arch<<771<<endl;
	arch<<28<<endl;	arch<<"Gilbert"<<endl;	arch<<700<<endl;
	arch<<7<<endl;	arch<<"Caseros"<<endl;	arch<<760<<endl;
	arch<<53<<endl;	arch<<"Pueblo Liebig"<<endl;	arch<<702<<endl;
	arch<<69<<endl;	arch<<"Ubajay"<<endl;	arch<<108<<endl;
	arch<<41<<endl;	arch<<"Los Charruas"<<endl;	arch<<797<<endl;
	arch<<45<<endl;	arch<<"Nogoya"<<endl;	arch<<1523<<endl;
	arch<<59<<endl;	arch<<"San Jose"<<endl;	arch<<255<<endl;
	arch<<74<<endl;	arch<<"Villa Alcaraz"<<endl;	arch<<301<<endl;
	arch<<21<<endl;	arch<<"Enrique Carbo"<<endl;	arch<<532<<endl;
	arch<<63<<endl;	arch<<"Santa Ana"<<endl;	arch<<893<<endl;
	arch<<48<<endl;	arch<<"Piedras Blancas"<<endl;	arch<<381<<endl;
	arch<<33<<endl;	arch<<"Hasenkamp"<<endl;	arch<<1227<<endl;
	arch<<80<<endl;	arch<<"Villa Mantero"<<endl;	arch<<640<<endl;
	arch<<70<<endl;	arch<<"Urdinarrain"<<endl;	arch<<1502<<endl;
	arch<<19<<endl;	arch<<"Diamante"<<endl;	arch<<1906<<endl;
	arch<<38<<endl;	arch<<"La Paz"<<endl;	arch<<1133<<endl;
	arch<<65<<endl;	arch<<"Santa Elena"<<endl;	arch<<1143<<endl;
	arch<<22<<endl;	arch<<"Estancia Grande"<<endl;	arch<<609<<endl;
	arch<<73<<endl;	arch<<"Victoria"<<endl;	arch<<1623<<endl;
	arch<<52<<endl;	arch<<"Pueblo General Belgrano"<<endl;	arch<<760<<endl;
	arch<<35<<endl;	arch<<"Herrera"<<endl;	arch<<717<<endl;
	arch<<58<<endl;	arch<<"San Jaime de la Frontera"<<endl;	arch<<802<<endl;
	arch<<82<<endl;	arch<<"Villa Urquiza"<<endl;	arch<<1004<<endl;
	arch<<50<<endl;	arch<<"Pronunciamiento"<<endl;	arch<<461<<endl;
	arch<<2<<endl;	arch<<"Aldea Maria Luisa"<<endl;	arch<<532<<endl;
	arch<<46<<endl;	arch<<"Oro Verde"<<endl;	arch<<1204<<endl;
	arch<<36<<endl;	arch<<"Ibicuy"<<endl;	arch<<990<<endl;
	arch<<79<<endl;	arch<<"Villa Hernandarias"<<endl;	arch<<1160<<endl;
	arch<<1<<endl;	arch<<"Aldea Brasilera"<<endl;	arch<<809<<endl;
	arch<<64<<endl;	arch<<"Santa Anita"<<endl;	arch<<192<<endl;
	arch<<17<<endl;	arch<<"Conscripto Bernardi"<<endl;	arch<<763<<endl;
	arch<<66<<endl;	arch<<"Sauce de Luna"<<endl;	arch<<231<<endl;
	arch<<49<<endl;	arch<<"Primero de Mayo"<<endl;	arch<<652<<endl;
	arch<<12<<endl;	arch<<"Colonia Ayui"<<endl;	arch<<704<<endl;
	arch<<29<<endl;	arch<<"Gobernador Macia"<<endl;	arch<<1548<<endl;
	arch<<37<<endl;	arch<<"La Criolla"<<endl;	arch<<535<<endl;
	arch<<83<<endl;	arch<<"Villaguay"<<endl;	arch<<1667<<endl;
	arch<<75<<endl;	arch<<"Villa Clara"<<endl;	arch<<480<<endl;
	arch<<3<<endl;	arch<<"Aldea San Antonio"<<endl;	arch<<564<<endl;
	arch<<8<<endl;	arch<<"Ceibas"<<endl;	arch<<904<<endl;
	arch<<15<<endl;	arch<<"Concepcion del Uruguay"<<endl;	arch<<1793<<endl;
	arch<<9<<endl;	arch<<"Cerrito"<<endl;	arch<<904<<endl;
	arch<<60<<endl;	arch<<"San Jose de Feliciano"<<endl;	arch<<987<<endl;
	arch<<27<<endl;	arch<<"General Ramirez"<<endl;	arch<<641<<endl;
	arch<<40<<endl;	arch<<"Libertador San Martin"<<endl;	arch<<520<<endl;
	arch<<67<<endl;	arch<<"Segui"<<endl;	arch<<487<<endl;
	arch<<11<<endl;	arch<<"Colonia Avellaneda"<<endl;	arch<<1768<<endl;
	arch<<76<<endl;	arch<<"Villa del Rosario"<<endl;	arch<<900<<endl;
	arch<<55<<endl;	arch<<"Rosario del Tala"<<endl;	arch<<1392<<endl;
	arch<<25<<endl;	arch<<"General Campos"<<endl;	arch<<348<<endl;
	arch<<47<<endl;	arch<<"Parana"<<endl;	arch<<1987<<endl;
	arch<<62<<endl;	arch<<"San Salvador"<<endl;	arch<<510<<endl;
	arch<<32<<endl;	arch<<"Gualeguaychu"<<endl;	arch<<1720<<endl;
	arch<<5<<endl;	arch<<"Basavilbaso"<<endl;	arch<<890<<endl;
	arch<<10<<endl;	arch<<"Chajari"<<endl;	arch<<592<<endl;
	arch<<20<<endl;	arch<<"El Pingo"<<endl;	arch<<429<<endl;
	
	arch.close();

	return 0;
}

